name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    frontend-test:
      runs-on: ubuntu-latest
      steps:
       - name: Get the code 
         uses: actions/checkout@v4

       - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd client && npm install

      - name: Run tests
        run: cd client && npx vitest run src/test/

      - name: Build check
        run: cd client && npm run build
EOF